In [1]:
import numpy as np

In [2]:
list1 = [1 ,2, 3]
a = np.array(list1)
a

array([1, 2, 3])

In [3]:
print(a.shape)

(3,)


In [4]:
b = np.array([[1, 2, 3, 4], [5, 6, 7,8]])
print(b.shape)

(2, 4)


In [5]:
print(b[0, 0])

1


In [6]:
print(type(b))

<class 'numpy.ndarray'>


In [7]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
b[1, 2]

np.int64(7)

In [9]:
a = np.array( [ 1, 2.3, 3, 4 ] )
print(a)

[1.  2.3 3.  4. ]


In [10]:
a = np.array( [ 1, '2', '3', 4 ] )
print(a)

['1' '2' '3' '4']


In [11]:
a = np.array( [ 1, 2, '3', 4 ] )
print(a)

['1' '2' '3' '4']


In [12]:
a1 = np.array( [ 1, 2, 3, 4, 5 ])
a2 = np.array( [ [ 1, 2, 3, 4 ] , [ 1, 2, 3, 4 ] ] )
a3 = np.array( [ [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ,
                 [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ,
                 [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ] )

In [13]:
a1

array([1, 2, 3, 4, 5])

In [14]:
a2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [15]:
a3

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [16]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [17]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(5,)
(2, 4)
(3, 2, 3)


In [18]:
a = np.zeros((3),dtype='int64')
print(a)

[0 0 0]


In [19]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [20]:
a = np.zeros((2,2),dtype='int64')
print(a)

[[0 0]
 [0 0]]


In [21]:
a = np.zeros((2,2,2),dtype='int64')
print(a)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [22]:
a = np.zeros((3),dtype='int64')
print(a)

[0 0 0]


In [23]:
a = np.ones((3))
print(a)

[1. 1. 1.]


In [24]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
a = np.full((3),1,dtype='int64')
print(a)

[1 1 1]


In [26]:
a = np.full((3),10,dtype='int64')
print(a)

[10 10 10]


In [27]:
a = np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


In [28]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
a = range(0, 10, 2)
a

range(0, 10, 2)

In [30]:
print(a)

range(0, 10, 2)


In [31]:
print(np.array(list(a)))

[0 2 4 6 8]


In [32]:
a = np.arange(0, 10 ,2)
print(a)

[0 2 4 6 8]


In [33]:
a = np.array(range(12)).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
a = np.arange(12).reshape((3,-1))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
a = np.arange(12).reshape((6,-1))
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [37]:
a = np.arange(12).reshape((-1,3)) # 열의 개수를 3으로 고정해준 문장임
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [38]:
lst = [[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a = arr[0:2, 0:2] # 행에대해서 0부터 2까지 그럼 2는 제외 / 열에 대해서 0부터 2까지 그럼 2는 제외
a

array([[1, 2],
       [4, 5]])

In [40]:
a = arr[1:, 1:]
a

array([[5, 6],
       [8, 9]])

In [41]:
a = [0,1,2,3]
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [42]:
print(a[1:4:2])

[1, 3]


In [43]:
a = np.array([0,1,2,3])
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [44]:
print(a[1:4:2])

[1 3]


In [45]:
print(a[::-1]) # 역순으로 / 왜냐? / -1이 끝에서 부터 시작하는 의미이기 때문에

[3 2 1 0]


In [46]:
print(b[0][1])

1


In [47]:
print(b[0,1])

1


In [48]:
print(b[:2])

[[0 1 2 3]
 [4 5 6 7]]


In [49]:
print(b[:,0]) # 모든 행에 /0열 에 대한 내용

[0 4 8]


In [50]:
print(b[0,:]) # 0 행에 /모든 열

[0 1 2 3]


In [59]:
print(b[[0,2], :]) # 0행 모든열  2행 모든열

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [60]:
print(b[[2,0], :])

[[ 8  9 10 11]
 [ 0  1  2  3]]


In [58]:
b_5 = b > 5 # b_5에서 b 가 5보다 크면 트루에 해당한느 데이터만 추출 가능
print(b_5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [56]:
print(b[b_5])

[ 6  7  8  9 10 11]


In [63]:
print(b[[0,1],[1,2]])    # 정수 인덱싱 6페이지 # 0행 1열 / 1행 2열

[1 6]


In [62]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
print(b[[0,1,2],[1,2,0]]) 

[1 6 8]


In [65]:
# broadcasting 브로드캐스팅

In [66]:
a = np.array([0,1,2,3])
c = np.arange(4)
print(a)
print('----------')
print(c)

[0 1 2 3]
----------
[0 1 2 3]


In [67]:
print(c + 1)

[1 2 3 4]


In [68]:
print(a + c)

[0 2 4 6]


In [69]:
d = np.zeros((2,2,4)) # 2행 4열이 2개..?
print(d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [70]:
print(d + c)

[[[0. 1. 2. 3.]
  [0. 1. 2. 3.]]

 [[0. 1. 2. 3.]
  [0. 1. 2. 3.]]]


In [74]:
a = [0,1,2,3] # list + list는 연결이 되는데 나는 이걸 요소들끼리 더하게 해주고 시다 그럼 어떻게 해야할까?
b = [0,1,2,3]
print(a + b)

[0, 1, 2, 3, 0, 1, 2, 3]


In [80]:
d = [0,0,0,0]
for i in range(len(a)):
    d[i] = a[i] + b[i]

print(d)

[0, 2, 4, 6]


In [81]:
print(a + c)

[0 2 4 6]


In [82]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
np.split(a,2, axis=0) # 축방향을 생략하면 0이된다. 그래서 np.split(a,2) = np.split(a,2, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [88]:
np.split(a,(1,3)) 

# 구간의 의미 
# 튜플로 주어졌을 때
# [:1], [1:3], [3:]

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [91]:
np.split(a,2, axis=1) # 축방향을 기준으로 1이 되면 2개로 나눠짐

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [92]:
np.split(a,(1,3), axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [106]:
# h = horizontal 즉 수평을 의미하는데 ㅡ 이렇게 수평으로 자르지 않고 ㅣ 이렇게 수직응로 자른다
# v = virtical 의 경우도 반대로 수직으로 자르지 않고 자르는 것을 ㅡ 수평으로 자른다

In [107]:
splite1, splite2 = np.hsplit(a,2) # horizontal # 열을 자른다.

In [108]:
print("splite1"); print(splite1)

splite1
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [109]:
print("splite2"); print(splite2)

splite2
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [110]:
splite1, splite2 = np.vsplit(a,2) # virtical # 행을 자른다.

In [111]:
print("splite1"); print(splite1)

splite1
[[0 1 2 3]
 [4 5 6 7]]


In [112]:
print("splite2"); print(splite2)

splite2
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
 ## stack # 7페이지

In [119]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [120]:
stack0 = np.stack((a,a))
print(stack0.shape)

(2, 4, 4)


In [121]:
print(stack0)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]


In [122]:
stack1 = np.stack((a,a), axis=1)
print(stack1.shape)

(4, 2, 4)


In [123]:
print(stack1)

[[[ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [12 13 14 15]]]


In [125]:
print(np.vstack((a,a)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [127]:
print(np.hstack((a,a)))

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15]]


In [129]:
a = np.arange(9).reshape(3,3)
b = 2 * a
print(a)
print('-----------')
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-----------
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [130]:
print(np.hstack((a,b)))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [131]:
print(np.concatenate((a,b), axis=1))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [132]:
print(np.vstack((a,b)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [133]:
print(np.concatenate((a,b), axis=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [134]:
# # # 여기까지 스택 연산

In [140]:
#flatten / ravel 연산

In [141]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [150]:
b = a.flatten() # 데이터를 하나 더 복사해서 사본을 보여주는 놈
print(b)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]


In [151]:
c = a.ravel() # 반면에 라벨은 a와 c 동일한데이터를 보이게 하고 2차원을 1차원으로 바꿔서 보여준다.
print(c)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]


In [152]:
b[0] = 100
print(b)
print(a)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


In [153]:
c[0] = 100
print(c)
print(a)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


In [ ]:
# 졸지말고공부해라???

In [154]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [155]:
print(a+b)

[5 7 9]


In [156]:
print(np.add(a, b))

[5 7 9]


In [157]:
print(a * b)

[ 4 10 18]


In [160]:
print(np.multiply(a, b))

[[ 1  4]
 [ 9 16]]


In [159]:
lst1 = [[1,2], [3,4]]
lst2 = [[1,2], [3,4]]
a = np.array(lst1)
b = np.array(lst2)
c = np.dot(a,b)
print(c)

[[ 7 10]
 [15 22]]


In [161]:
a = np.array([[1,2],[3,4]])
s = np.sum(a, axis=0)
print(s)

[4 6]


In [163]:
s = np.sum(a, axis=1)
print(s)

[3 7]


In [164]:
s = np.prod(a)
print(s)

24


In [165]:
s = np.prod(a, axis=0)
print(s)

[3 8]


In [166]:
s = np.prod(a, axis=1)
print(s)

[ 2 12]


In [167]:
# 난수 random

In [168]:
np.random.seed(0)         
# 나중에 머신러닝을 할 때, 각 모델들 마다 주요 파라매터의 최적값을 찾기 위해서 학습을 하는데 
# 값이 달라지면 학습의 내용이 달라지고 초기화 되기에 시드를 사용하는 것이다.
print(np.random.rand(5))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [169]:
print(np.random.rand(5))

[0.64589411 0.43758721 0.891773   0.96366276 0.38344152]


In [171]:
print(np.random.rand(5))

[0.33739616 0.64817187 0.36824154 0.95715516 0.14035078]


In [172]:
x = np.arange(10)
print(x)
print('-------------------------------------')
np.random.seed(0)
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
-------------------------------------
[2 8 4 9 1 6 7 3 0 5]


In [175]:
z = np.random.choice(np.arange(5), 3, replace=False)
print(z)

[0 2 4]


In [176]:
z = np.random.choice(10, 20, replace=True)
print(z)

[3 7 0 1 9 9 0 4 7 3 2 7 2 0 0 4 5 5 6 8]


In [177]:
z = np.random.choice(5, 50, p=[0.1, 0, 0.3, 0.6, 0])
print(z)

[3 3 3 2 3 3 0 3 3 2 2 2 2 3 3 3 2 2 2 3 2 3 2 2 2 3 2 2 2 3 0 3 0 3 3 3 3
 3 0 2 2 2 2 2 3 0 3 3 2 3]


In [178]:
x = np.random.randint(1, 100, size=5)
x = np.unique(a)
print(x)

[1 2 3 4]


In [180]:
x, cnt = np.unique(a, return_counts=True)
print(x, cnt, sep=",")


[1 2 3 4],[1 1 1 1]


In [186]:
x = np.array([18,5,10,23,19,-8,10,0,0,5,2])
print(len(x))
print(sum(x))
print(np.size(x))
print(np.sum(x))
print(np.mean(x))
print(np.var(x))
print(np.std(x))
print(np.max(x))
print(np.min(x))
print(np.median(x))
print(np.sort(x))

11
84
11
84
7.636363636363637
80.9586776859504
8.997704023024452
23
-8
5.0
[-8  0  0  2  5  5 10 10 18 19 23]


In [187]:
x = [18,5,10,23,19,-8,10,0,0,5,2]
print(len(x))
print(sum(x))
print(np.size(x))
print(np.sum(x))
print(np.mean(x))
print(np.var(x))
print(np.std(x))
print(np.max(x))
print(np.min(x))
print(np.median(x))
print(np.sort(x))

11
84
11
84
7.636363636363637
80.9586776859504
8.997704023024452
23
-8
5.0
[-8  0  0  2  5  5 10 10 18 19 23]
